upsource:
    # build: .
    image: esycat/upsource
    container_name: upsource
    restart: always
    ports:
        - 80:8080
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data/upsource:/var/lib/upsource
        - /data/upsource/conf:/opt/upsource/conf
    ulimits:
        memlock: -1
        nofile: 100000
        nproc: 32768
